<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="DESKTOP-TBLA2PR" failures="1" tests="1" name="Test(failed)" time="0.232" errors="0" timestamp="2023-06-24T19:38:53 IST">
  <testcase classname="testNGDemo.TestScenario1" name="first_testcase" time="0.039">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Hello1] but found [Hello]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Hello1] but found [Hello]
at testNGDemo.TestScenario1.first_testcase(TestScenario1.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- first_testcase -->
  <testcase classname="testNGDemo.TestScenario1" name="second_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- second_testcase -->
  <testcase classname="testNGDemo.TestScenario1" name="forth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- forth_testcase -->
  <testcase classname="testNGDemo.TestScenario1" name="fifth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- fifth_testcase -->
  <testcase classname="testNGDemo.TestScenario1" name="third_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- third_testcase -->
  <testcase classname="testNGDemo.TestScenario1" name="sixth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- sixth_testcase -->
</testsuite> <!-- Test(failed) -->
